### ISSUE TITLE
Nouvelle page RECORDS

### ISSUE THREAD

**Issue by pylscblt** [pylscblt/top7#1]
Salut Pyl,

Je reviens sur ma demande d’avoir une fenêtre pour les records inter-saisons
Je te la formule ici (je n’ai plus le lien pour indefero) :

Dans la fenêtre « **STATS Inter-EQUIPES !** »
Ajouter un bouton « **RECORDS Inter-SAISONS !** » en couleur orange ou rouge à côté du bouton « Retour au TOP7 »

L’accès à ce bouton amènera à une fenêtre qui sera une copie de celle « STATS Inter-EQUIPES »
Avec le titre « **RECORDS (toutes saisons confondues)** »
Et les mêmes onglets hormis celui « Moyenne »
et dans lesquels ils faudrait ajouter la colonne « Saison » placée en 3è position derrière équipe ou joueur… selon.
Virer toutes les colonnes inutiles au tri (non en gras) pour alléger l’affichage

Les requêtes sont exactement les mêmes sauf qu’il faut les ouvrir à toute les saisons, bien sûr.
ET n’afficher que les trois premiers (avec les ex-aequo du 3è, s’il y a)

Voilà dans un premier temps

Est-ce plus compliqué que ça m’en a l’air ?

Bonne journée.

**Comment by pylscblt-test** [comment]
Salut Pyl !

Super ! C’est un bon début,  merci !

A première vue, faudra alléger… 

- Mettre le mot SAISON en français stp
- Virer l’onglet MOY qui n’a pas d’intérêt
- Virer les colonnes qui ne sont pas en gras
- Surligner le premier, détenteur du record
- Ne garder que les 3 premiers rangs (<4)
- Un joueur ou équipe ne peut apparaître qu’une fois (à voir plus tard si compliqué)
- il faudrait ajouter le bouton « retour au TOP 7 » devant celui « Stats inter-équipes » (plus tard)
- Faudra aussi qu’on trouve une autre couleur que rouge (or ?)
 
Voilà en gros,

**Comment by pylscblt-test** [comment]
* Pour les ex-aequo, c’est pas grave car il ne devrait pas vraiment y en avoir
* Rmq : sur les STATS inter équipes, tu mets des rangs ex-aequo alors qu’ils ne le sont que sur un critère
* Par contre, y a une erreur sur les Records par équipe… tu cumules plusieurs saisons, on ne devrait jamais dépasser 700 points sur une saison pour une équipe…
* Il ne faut intégrer que les saisons normalement terminées (hors en cours et annulées)
* Pour le record des 14 ! … le rang doit tenir compte de tous les critères de tri (idem première rmq)
* Le plus simple est que tu ne le gères pas et laisses les rangs par ligne 1, 2, 3
* Pour le surlignage des trois lignes, est-il possible de ne mettre sur fond jaune que la première ligne en gras et les deux suivantes sur fond gris ?
* En tout cas, merci, c’est un bon début…
* Ça va être impossible pour moi d’atteindre 86 points pour te battre au record 14 !:/

**Comment by pylscblt-test** [comment]
* Faut juste que tu ne gères pas le rang # et laisse afficher 1, 2 et 3
* Et si tu peux afficher la première ligne sur fond jaune et les deux suivantes sur fond gris.
* (sinon afficher la première ligne en gras et écrite en rouge)
* A noter que les liens en bas « légendes » et « fun » ne donnent rien. Ils ne sont pas indispensables.
* Autre rmq
* Que ce soit sur STATS inter-EQUIPES ou RECORDS inter-SAISONS. L’affichage de l’onglet sur lequel on est apparaît juste en gras. Ce qui ne le différencie pas beaucoup des autres
* Plus flagrant sur la page RECORDS, on ne sait plus de quel onglet il s’agit.
* Est-il possible d’accentuer la différence ?
* Trouver un fond de couleur plus nuancée en plus du gras
* Une couleur de police différente sur l’onglet en cours
* Rmq2 : quand on arrive sur la page, l’onglet « Par joueur » n’est carrément pas différencié

**Comment by pylscblt-test** [comment]
- Changer le titre du bouton « RECORDS inter-SAISONS » par « RECORDS & PALMARÈS »
- Ajouter le fichier image des Palmares fourni
- Exclure la saison en cours et les saisons annulées des sélections des Records
- Si possible : exclure la ligne d’un joueur apparaissant 2 fois sur un podium pour laisser la place au suivant de la liste

**Comment by pylscblt** [comment]
La nouvelle page **RECORDS&PALMARES** est approuvée par Antonio 👍
