### ISSUE TITLE
Sélection classement J1 identique au classement final de la dernière saison

### ISSUE THREAD

**Issue by pylscblt-test** [pylscblt/top7#10]
Pourrais-tu opérer une requête afin de modifier les heures d’inscription  pour avoir l’ordre de sélection conforme au classement final de la saison passée, à savoir :

Bernie
Pyl
Raoul
Marvellous
Mr Rougerie
Revel
Bibi
 
Cela pourrait éventuellement se faire automatiquement dès lors qu’une équipe est reconduite à l’identique d’une saison sur l’autre.

Merci et bon retour sous le cagnard… Demain, le froid revient 😉
Tonio

**Comment by pylscblt** [comment]
Bon c'est un peu bricolé. Il y avait déjà un critère de tri avec les dates d'inscription. J'ai modifié à la main les dates pour retrouver l'ordre de la saison dernière.
Voilà c'est pas super top. Je corrigerais plus tard pour que ça soit automatique comme tu le dis 😛
