### ISSUE TITLE
Store Emoji in comment part

### ISSUE THREAD

**Issue by pylscblt-test** [pylscblt/top7#11]
* Gabi a fort justement remarqué que les emojis n'appraissent pas dans le forum.
* Pb de setting de charset au niveau mysql 
* Voir [ici](https://stackoverflow.com/questions/39463134/how-to-store-emoji-character-in-mysql-database)

**Comment by pylscblt** [comment]
SQL statements to execute
```
ALTER DATABASE topseven CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE forum CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE forum MODIFY comment TEXT CHARSET utf8mb4;
```
SQL connection charset to change
```
        $charset  = "utf8mb4";
        $pdo = new PDO("mysql:dbname=$database;host=$server;charset=$charset", $user, $password);
```

**Comment by pylscblt-test** [comment]
Pas de retours ! 
C'est OK.
