### ISSUE TITLE
Reprendre l'ordre de la finale de la précédente saison pour la 1ere journée 

### ISSUE THREAD

**Issue by pylscblt-test** [pylscblt/top7#16]
Pour garder l'ordre des joueurs pour la 1ere journée d'une équipe déjà inscrite, plutôt que de prendre un ordre aléatoire. L'idée serait de fixer cet ordre lors de la réinscription de l'équipe à la nouvelle saison.

**Comment by pylscblt** [comment]
A voir pour la saison prochaine.

**Comment by pylscblt** [comment]
Correction validée pour cette saison 2024-2025.

**Comment by pylscblt** [comment]
- Correction validée pour cette saison 2024-2025.
